Refactored hubs and merged hub search with menu
Casp7654/XPower pull request #19
Opened 2022-09-27 10:19 UTC by Geefy

2022-09-27 11:25 UTC, Ripiter commented on source/webclient/XPower_WebClient/src/app/Services/hub.service.ts
> +    let a = new HubDevice();
better name

2022-09-27 11:26 UTC, Ripiter commented on source/webclient/XPower_WebClient/src/app/Components/hub/hub.component.ts
> +  ondblclickevent(event : any): void {
camel case

2022-09-27 11:29 UTC, Ripiter commented on source/webclient/XPower_WebClient/src/app/Pages/hub-searcher/hub-searcher.component.scss
> +    color:rgba(27,40,69,1);
create global css for button 
with color
and with backgroud

2022-09-27 11:31 UTC, Ripiter requested changes
few comments

2022-09-27 11:45 UTC, blackout1471 commented
Where is unit tests?

2022-09-28 10:28 UTC, blackout1471 requested changes

2022-09-28 10:28 UTC, blackout1471 commented on source/webclient/XPower_WebClient/src/app/Converters/Json/SocketDeviceJsonRequestConverter.ts
> +
Needs comments

2022-09-28 10:33 UTC, blackout1471 approved these changes

2022-09-28 10:49 UTC, Ripiter approved these changes
looks better

2022-09-28 10:50 UTC, merged